/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Test;
import java.util.GregorianCalendar;

import static org.junit.jupiter.api.Assertions.*;

class LivroTeste {
	
	final String fraseErro = "Valor inválido.";
	
    @Test void periodoConstrutorPadrao() {
        Livro livroTeste = new Livro();

        livroTeste.setTitulo("Admirável mundo novo");
        livroTeste.setAutores(new String[] {"Aldous Huxley"});
        livroTeste.setDescricao("Admirável Mundo Novo é um romance escrito por Aldous Huxley e publicado em 1932. A história se passa em Londres no ano 2540, o romance antecipa desenvolvimentos em tecnologia reprodutiva, hipnopedia, manipulação psicológica e condicionamento clássico, que se combinam para mudar profundamente a sociedade.");
        livroTeste.setPaginas(252);
        livroTeste.setDataPublicacao(new GregorianCalendar(1932, 3, 6));
        livroTeste.setEditora("Globo Livros");
        livroTeste.setIsbn("9788525056443");

        System.out.println(livroTeste.getTitulo());
        System.out.println(livroTeste.getAutores());
        System.out.println(livroTeste.getDescricao());
        System.out.println(livroTeste.getPaginas());
        System.out.println(livroTeste.getDataPublicacao());
        System.out.println(livroTeste.getEditora());
        System.out.println(livroTeste.getIsbn());

        assertEquals("Período Moderno.", livroTeste.descobrirPeriodo(), fraseErro);
    }
    @Test void periodoConstrutorTres() {
    	Livro livroTeste = new Livro("Utopia", new String[] {"Thomas More"}, "Libellus vere aureus, nec minus salutaris quam festivus, de optimo rei publicae statu deque nova insula Utopia, mais conhecido simplesmente como Utopia, é um livro de 1516 escrito por Thomas Morus. Escrito em latim, foi sua principal obra literária.", new GregorianCalendar(1516, 6, 18));

        assertEquals("Período não registrado no sistema.", livroTeste.descobrirPeriodo(), fraseErro);
    }
    @Test void periodoConstrutorCompleto() {
    	Livro livroTeste = new Livro("O Diário de Anne Frank", new String[] {"Anne Frank"}, "O Diário de Anne Frank é um livro escrito por Anne Frank entre 12 de junho de 1942 e 1.º de agosto de 1944 durante a Segunda Guerra Mundial. É conhecido por narrar momentos vivenciados pelo grupo de judeus confinados em um esconderijo durante a ocupação nazista dos Países Baixos.", 352, new GregorianCalendar(1947, 7, 25), "Record", "8501044458");

        System.out.println(livroTeste.toString());

        assertEquals("Período Pós-Moderno.", livroTeste.descobrirPeriodo(), fraseErro);
    }
    
}